# shallow clone
clone_depth: 5

environment:
  BUILD_PASSWORD:
    secure: EXGNlWKJsCtbeImEJ5EP9qrxZ+EqUFfNy+CP61nDOMA=

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 ..
  - cd ..

build:
  project: build/citra.sln
  parallel: true

test_script:
  - cd build && ctest -VV -C Release && cd ..

on_success:
    # copying the needed QT Dlls is now done post build. See the CMakeLists.txt file in the citra-qt folder
  - ps: >
        if (!"$env:APPVEYOR_PULL_REQUEST_TITLE" -and ("$env:APPVEYOR_REPO_BRANCH" -eq "master"))
          {
            $GITDATE = $(git show -s --date=short --format='%ad') -replace "-",""
            $GITREV = $(git show -s --format='%h')

            # Build the installer
            $CMAKE_SOURCE_DIR = "$env:APPVEYOR_BUILD_FOLDER"
            $CMAKE_SOURCE_DIR = "C:/dev/citra"
            $CMAKE_BINARY_DIR = "$CMAKE_SOURCE_DIR/build"
            $BIN_FOLDER = "$CMAKE_BINARY_DIR/bin/Release"
            $SQUIRREL_DIR = "$CMAKE_BINARY_DIR/squirrel.win"
            $SQUIRREL_RELEASE_DIR = "$SQUIRREL_DIR/Release"
            $SQUIRREL_BUILD_DIR = "$SQUIRREL_DIR/Build"
            $SQUIRREL_BIN_DIR = "$SQUIRREL_DIR/lib/net45"
            # make the path we'll copy the output to post build
            New-Item -ItemType Directory -Force -Path $SQUIRREL_BIN_DIR

            # Copy the files to the folder for nuget to package
            echo $BIN_FOLDER
            echo $SQUIRREL_BIN_DIR
            Copy-Item -path "$BIN_FOLDER/*" -exclude "*.pdb" -destination $SQUIRREL_BIN_DIR

            # build the nuget file
            cmd /c "$CMAKE_BINARY_DIR/nuget/nuget.exe pack $CMAKE_BINARY_DIR/citra.nuspec ^
                    -BasePath $SQUIRREL_BUILD_DIR -OutputDirectory $SQUIRREL_BUILD_DIR"
            echo "Building squirrel"
            cmd /c "$CMAKE_BINARY_DIR/squirrel/squirrel.exe --releasify $SQUIRREL_BUILD_DIR/Citra.0.1.0.nupkg ^
                    --releaseDir=$SQUIRREL_RELEASE_DIR --icon=$CMAKE_SOURCE_DIR/dist/citra.ico ^
                    --loadingGif=$CMAKE_SOURCE_DIR/dist/output.gif"

            $GITDATE = $(git show -s --date=short --format='%ad') -replace "-",""
            $GITREV = $(git show -s --format='%h')
            # Where are these spaces coming from? Regardless, let's remove them
            $BUILD_NAME = "citra-${GITDATE}-${GITREV}-windows-amd64.7z" -replace " ",""
            $BUILD_NAME_NOQT = "citra-noqt-${GITDATE}-${GITREV}-windows-amd64.7z" -replace " ",""
            # Zip up the build folder and documentation
            7z a $BUILD_NAME .\build\bin\release\* .\license.txt .\README.md
            # Do a second archive with only the binaries (excludes dlls) and documentation
            7z a $BUILD_NAME_NOQT .\build\bin\release\*.exe .\license.txt .\README.md


            # Download WinSCP and upload to server
            choco install winscp.portable
            WinSCP.exe /command `
                "option batch abort" `
                "option confirm off" `
                "open sftp://citra-builds:${env:BUILD_PASSWORD}@builds.citra-emu.org -hostkey=*" `
                "put $BUILD_NAME /citra/nightly/windows-amd64/" `
                "put $BUILD_NAME_NOQT /citra/nightly/windows-noqt-amd64/" `
                "exit"
          }
